#!/usr/bin/env bash

mpich (){
  pushd mpich-3.2
    ./mpich-3.2/configure --disable-fortran --prefix=$(pwd)/build
  popd
}

boost (){
  PATH=$(pwd)/mpich-3.2/build/bin:$PATH
  LD_LIBRARY_PATH=$(pwd)/mpich-3.2/build/lib:$LD_LIBRARY_PATH
  pushd boost_1_60_0
    ./bootstrap.sh
    git checkout project-config.jam
    ./b2 --with-mpi --with-serialization -j 8
    ./b2 install --prefix=${pwd}/build -j 8
  popd
}

upload (){
  nodejs scaleway.js > hostfile
}

run (){
  mpirun -npernode 4 release/asn2 -size 10000
}

build (){
  make -C build
}

hostfile (){
  nodejs scaleway.js > hostfile
}

release(){
  cmake -DCMAKE_BUILD_TYPE=Release -B./build -H.
}

benchmark_test(){
    ./benchmark.sh 8000 1000 12000
}

benchmark(){
    ./benchmark.sh 40000000 100000 48000000
}

$@
